server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys
    username: root
    password: somePassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations: classpath:DDL_STUDENTS.sql
      data-locations: classpath:DML_STUDENTS.sql
      mode: always
spring.jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  hibernate.ddl-auto: update
  show-sql: true

